version: '3'
networks:
  php-network:
    internal: false
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-apache-php-app
    volumes:
      - type: bind
        source: ./app/src
        target: /var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=Lift-extract-anthony-92
      - MYSQL_DATABASE=php
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=982hhfn9i24ugh925hg9235thrg39w28014t08hij
      - MYSQL_HOST=php-mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - php-network
  mysql:
    container_name: php-mysql
    platform: linux/x86_64
    networks:
      - php-network
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: Lift-extract-anthony-92
      MYSQL_DATABASE: php
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 982hhfn9i24ugh925hg9235thrg39w28014t08hij
    ports:
      - "3306"
    expose:
      - '3306'
    # volumes:
    #   - PhpMysqlVolume:/var/lib/mysql

  adminer:
    container_name: adminer
    networks:
      - php-network
    image: adminer
    ports:
      - "8081:8080"
